### ISSUE TITLE
Option to disable "Extracting Rounds" feature

### ISSUE THREAD

**Issue by RaynorCZE** [potatoes1286/BetterMagRelease#4]
Hi,
Would it be possible to add an option to disable "Extracting Rounds" option?
I am mainly asking because there are some other mods (ex. Meatyceiver) that are giving a chance that not all rounds eject (Including Break action weapons).

I personally would rather have the chance to Eject rather than no chance.

Thanks in advance for reply

**Comment by potatoes1286** [comment]
Does the "enable extracting rounds" config in the mod's config not disable it?

**Comment by RaynorCZE** [comment]
> Does the "enable extracting rounds" config in the mod's config not disable it?

Do you mean in in-gmae mod menu or do you mean in mod's ini file? ... I have been looking to the ingame menu and I didn't see the "Cog icon" to enter the config menu ... let me check the ini files

**Comment by RaynorCZE** [comment]
> Does the "enable extracting rounds" config in the mod's config not disable it?

Ok ... Yep that did it ... I am really sorry for not checking properly

**Comment by potatoes1286** [comment]
No worries.
